#!/usr/bin/env bash
set -euo pipefail

# ═══════════════════════════════════════════════════════════════════════
# setup-karimsw.sh — Bootstrap the KarimSW agent system into any repo
# Usage: setup-karimsw.sh <company-name> [--force]
# ═══════════════════════════════════════════════════════════════════════

# ─── Phase 0: Validate ────────────────────────────────────────────────

COMPANY_NAME="${1:-}"
FORCE_FLAG="${2:-}"

if [[ -z "$COMPANY_NAME" ]]; then
  echo "Usage: setup-karimsw.sh <company-name> [--force]"
  echo ""
  echo "  company-name  Name for the new company (e.g. MyCompany)"
  echo "  --force       Overwrite existing files"
  exit 1
fi

SOURCE="${CONNECTSW_SOURCE:-/Users/tamer/Desktop/Projects/Claude Code creates the SW company}"
TARGET="$(pwd)"

if [[ ! -d "$SOURCE/.claude" ]]; then
  echo "ERROR: Source directory not found: $SOURCE/.claude"
  echo "Set CONNECTSW_SOURCE env var to the KarimSW repo root."
  exit 1
fi

if [[ ! -d "$TARGET/.git" ]]; then
  echo "ERROR: Target is not a git repo: $TARGET"
  echo "Run 'git init' first."
  exit 1
fi

echo "╔══════════════════════════════════════════════════╗"
echo "║   KarimSW Agent System Setup                   ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""
echo "  Company:  $COMPANY_NAME"
echo "  Source:   $SOURCE"
echo "  Target:   $TARGET"
echo "  Mode:     ${FORCE_FLAG:-new install}"
echo ""

# ─── Phase 1: Copy directories ────────────────────────────────────────

if [[ "$FORCE_FLAG" == "--force" ]]; then
  RSYNC_FLAGS="-a --quiet"
else
  RSYNC_FLAGS="-a --quiet --ignore-existing"
fi

copy_dir() {
  local src="$1"
  local dst="$2"
  if [[ ! -d "$src" ]]; then
    return 0
  fi
  mkdir -p "$dst"
  rsync $RSYNC_FLAGS "$src/" "$dst/"
}

copy_file() {
  local src="$1"
  local dst="$2"
  if [[ ! -f "$src" ]]; then
    return 0
  fi
  if [[ "$FORCE_FLAG" == "--force" ]] || [[ ! -f "$dst" ]]; then
    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
  fi
}

echo "Phase 1: Copying agent system directories..."

# 21 .claude/ subdirectories
CLAUDE_DIRS=(
  agents
  commands
  engine
  workflows
  protocols
  quality-gates
  scripts
  standards
  templates
  advanced-features
  architecture
  resource-management
  dashboard
  monitoring
  checkpointing
  security
  mcp-tools
  audit
  checklists
  tests
)

for dir in "${CLAUDE_DIRS[@]}"; do
  copy_dir "$SOURCE/.claude/$dir" "$TARGET/.claude/$dir"
  echo "  ✓ .claude/$dir"
done

# Orchestrator (excluding state.yml)
mkdir -p "$TARGET/.claude/orchestrator"
rsync $RSYNC_FLAGS --exclude="state.yml" "$SOURCE/.claude/orchestrator/" "$TARGET/.claude/orchestrator/"
echo "  ✓ .claude/orchestrator (excluding state.yml)"

# CLAUDE.md
copy_file "$SOURCE/.claude/CLAUDE.md" "$TARGET/.claude/CLAUDE.md"
echo "  ✓ .claude/CLAUDE.md"

# README-UTILITIES.md
copy_file "$SOURCE/.claude/README-UTILITIES.md" "$TARGET/.claude/README-UTILITIES.md"
echo "  ✓ .claude/README-UTILITIES.md"

# .specify/ (spec-kit framework)
copy_dir "$SOURCE/.specify" "$TARGET/.specify"
echo "  ✓ .specify/"

# .github/ (selective — skip product-specific CI workflows)
copy_dir "$SOURCE/.github/ISSUE_TEMPLATE" "$TARGET/.github/ISSUE_TEMPLATE"
echo "  ✓ .github/ISSUE_TEMPLATE/"

copy_file "$SOURCE/.github/PULL_REQUEST_TEMPLATE.md" "$TARGET/.github/PULL_REQUEST_TEMPLATE.md"
echo "  ✓ .github/PULL_REQUEST_TEMPLATE.md"

copy_file "$SOURCE/.github/dependabot.yml" "$TARGET/.github/dependabot.yml"
echo "  ✓ .github/dependabot.yml"

# Command Center — core company dashboard (not a product, part of infrastructure)
if [[ -d "$SOURCE/products/command-center" ]]; then
  mkdir -p "$TARGET/products/command-center"
  rsync $RSYNC_FLAGS \
    --exclude="node_modules" \
    --exclude="dist" \
    --exclude=".vite" \
    --exclude="*.timestamp-*" \
    --exclude="test-results" \
    --exclude="playwright-report" \
    "$SOURCE/products/command-center/" "$TARGET/products/command-center/"
  echo "  ✓ products/command-center/ (company dashboard)"
fi

# .githooks/ (git safety hooks)
copy_dir "$SOURCE/.githooks" "$TARGET/.githooks"
if [[ -d "$TARGET/.githooks" ]]; then
  chmod +x "$TARGET/.githooks/"* 2>/dev/null || true
fi
echo "  ✓ .githooks/"

echo ""

# ─── Phase 2: Initialize fresh state ──────────────────────────────────

echo "Phase 2: Initializing fresh state..."

TODAY=$(date -u +%Y-%m-%dT%H:%M:%SZ)
TODAY_DATE=$(date -u +%Y-%m-%d)
GIT_USER=$(git config user.name 2>/dev/null || echo "TBD")

# state.yml (always fresh — never carry over product state)
cat > "$TARGET/.claude/orchestrator/state.yml" <<YAML
# Auto-generated by setup-karimsw.sh on $TODAY_DATE
company:
  name: "$COMPANY_NAME"
  founded: "$TODAY_DATE"
  ceo: "$GIT_USER"

products: {}

worktrees: []
pending_decisions: []
checkpoints: []

last_updated: "$TODAY"
YAML
echo "  ✓ .claude/orchestrator/state.yml"

# Memory system — carry over all accumulated knowledge
mkdir -p "$TARGET/.claude/memory/agent-experiences"
mkdir -p "$TARGET/.claude/memory/metrics"

# Copy documentation files
copy_file "$SOURCE/.claude/memory/memory-system.md" "$TARGET/.claude/memory/memory-system.md"
copy_file "$SOURCE/.claude/memory/relevance-scoring.md" "$TARGET/.claude/memory/relevance-scoring.md"

# Copy accumulated knowledge (patterns, decisions, learnings)
copy_file "$SOURCE/.claude/memory/company-knowledge.json" "$TARGET/.claude/memory/company-knowledge.json"
copy_file "$SOURCE/.claude/memory/decision-log.json" "$TARGET/.claude/memory/decision-log.json"
echo "  ✓ .claude/memory/company-knowledge.json (carried over)"
echo "  ✓ .claude/memory/decision-log.json (carried over)"

# Copy agent experiences (accumulated learnings per agent)
copy_dir "$SOURCE/.claude/memory/agent-experiences" "$TARGET/.claude/memory/agent-experiences"
echo "  ✓ .claude/memory/agent-experiences/ (carried over)"

# Copy performance metrics
copy_dir "$SOURCE/.claude/memory/metrics" "$TARGET/.claude/memory/metrics"
echo "  ✓ .claude/memory/metrics/ (carried over)"

# Empty audit trail
: > "$TARGET/.claude/audit-trail.jsonl"
echo "  ✓ .claude/audit-trail.jsonl (empty)"

# Clean PORT-REGISTRY.md
cat > "$TARGET/.claude/PORT-REGISTRY.md" <<'MDEOF'
# Port Registry

## Port Allocation Rules

| Range | Purpose |
|-------|---------|
| 3200-3299 | Frontend applications |
| 5100-5199 | Backend APIs |
| 8081-8099 | Mobile development servers |

## Port Assignment Process

When creating a new product, assign the next available port in each range.

## Registered Ports

### Frontend Applications (3200-3299)

| Port | Product | Status | URL |
|------|---------|--------|-----|
| 3213 | command-center | Active | http://localhost:3213 |

### Backend APIs (5100-5199)

| Port | Product | Status | URL |
|------|---------|--------|-----|
| 5109 | command-center | Active | http://localhost:5109 |

### Mobile Development (8081-8099)

| Port | Product | Status | URL |
|------|---------|--------|-----|

### Databases

Use default ports in Docker with unique container names per product.

## Quick Reference Commands

```bash
# Check if a port is in use
lsof -i :PORT_NUMBER

# Kill process on a port
kill -9 $(lsof -ti :PORT_NUMBER)
```
MDEOF
echo "  ✓ .claude/PORT-REGISTRY.md (clean)"

# COMPONENT-REGISTRY.md — carry over all shared components
copy_file "$SOURCE/.claude/COMPONENT-REGISTRY.md" "$TARGET/.claude/COMPONENT-REGISTRY.md"
echo "  ✓ .claude/COMPONENT-REGISTRY.md (carried over with shared components)"

echo ""

# ─── Phase 3: Replace company name ────────────────────────────────────

echo "Phase 3: Replacing 'KarimSW' with '$COMPANY_NAME'..."

# Derive lowercase name for package scopes (@karimsw/ → @mycompany/)
COMPANY_LOWER=$(echo "$COMPANY_NAME" | tr '[:upper:]' '[:lower:]')

# Portable sed -i (macOS vs Linux)
sed_inplace() {
  if [[ "$(uname)" == "Darwin" ]]; then
    sed -i '' "$@"
  else
    sed -i "$@"
  fi
}

# Find all text files in copied directories and replace KarimSW (both cases)
SEARCH_DIRS=("$TARGET/.claude" "$TARGET/.specify" "$TARGET/.githooks" "$TARGET/.github" "$TARGET/products/command-center")

for search_dir in "${SEARCH_DIRS[@]}"; do
  if [[ -d "$search_dir" ]]; then
    find "$search_dir" -type f \( \
      -name "*.md" -o -name "*.yml" -o -name "*.yaml" \
      -o -name "*.json" -o -name "*.sh" -o -name "*.ts" \
      -o -name "*.tsx" -o -name "*.js" -o -name "*.jsx" \
    \) 2>/dev/null | while read -r file; do
      # Replace PascalCase: KarimSW → CompanyName
      if grep -q "KarimSW" "$file" 2>/dev/null; then
        sed_inplace "s/KarimSW/$COMPANY_NAME/g" "$file"
      fi
      # Replace lowercase: karimsw → companyname (package scopes, paths)
      if grep -q "karimsw" "$file" 2>/dev/null; then
        sed_inplace "s/karimsw/$COMPANY_LOWER/g" "$file"
      fi
    done
  fi
done

echo "  ✓ KarimSW → $COMPANY_NAME (PascalCase)"
echo "  ✓ karimsw → $COMPANY_LOWER (lowercase — package scopes, paths)"
echo ""

# ─── Phase 4: Git setup ───────────────────────────────────────────────

echo "Phase 4: Configuring git..."

git -C "$TARGET" config core.hooksPath .githooks
echo "  ✓ Git hooks path set to .githooks"

# Ensure .gitignore exists and has required entries
touch "$TARGET/.gitignore"
GITIGNORE_ENTRIES=(
  ".claude/settings.local.json"
  ".claude/audit-trail.jsonl"
  ".DS_Store"
  "node_modules/"
  "dist/"
)
for entry in "${GITIGNORE_ENTRIES[@]}"; do
  if ! grep -qF "$entry" "$TARGET/.gitignore" 2>/dev/null; then
    echo "$entry" >> "$TARGET/.gitignore"
  fi
done
echo "  ✓ Updated .gitignore"

echo ""

# ─── Phase 5: Generate state ──────────────────────────────────────────

if [[ -d "$TARGET/products" ]] && [[ -f "$TARGET/.claude/scripts/generate-state.sh" ]]; then
  echo "Phase 5: Generating state from existing products..."
  bash "$TARGET/.claude/scripts/generate-state.sh" 2>/dev/null || echo "  ⚠ State generation skipped (no products yet)"
  echo ""
fi

# ─── Phase 6: Summary ─────────────────────────────────────────────────

DIR_COUNT=${#CLAUDE_DIRS[@]}

echo "╔══════════════════════════════════════════════════╗"
echo "║   Setup Complete!                                ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""
echo "Installed:"
echo "  • $((DIR_COUNT + 1)) agent system directories in .claude/"
echo "  • Command Center dashboard (products/command-center/)"
echo "  • Orchestrator with fresh state"
echo "  • Memory system with accumulated knowledge & decisions"
echo "  • Shared component registry (carried over)"
echo "  • Git safety hooks (pre-commit, post-commit)"
echo "  • spec-kit framework (.specify/)"
echo "  • GitHub templates (issues, PRs, dependabot)"
echo ""
echo "Next steps:"
echo "  1. Review .claude/CLAUDE.md and customize for your project"
echo "  2. Install Command Center deps:"
echo "     cd products/command-center && npm install"
echo "  3. Start the dashboard:"
echo "     cd products/command-center && npm run dev"
echo "     → Web: http://localhost:3213  API: http://localhost:5109"
echo "  4. Commit the setup: git add .claude .specify .githooks .github products/command-center"
echo "  5. Run /orchestrator to start using the agent system"
echo "  6. Create your first product:"
echo "     /orchestrator New product: [your idea]"
echo ""
